### Descomponer una matriz.
Quiere decir encontrar dos o más matrices que me ayuden a escribir la matriz original y que tengan ciertas propiedades.

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

Vamos a usar el símbolo de lambda para los autovalores, como tenemos dos autovalores en una matriz de 2X2 vamos a tener lambda 1 y 2: $\lambda_1$  y  $\lambda_2$

In [2]:
A = np.array([[3,2],[4,1]])
print(A)

[[3 2]
 [4 1]]


In [7]:
autovalores, autovectores = np.linalg.eig(A)
print("Autovalores: ",autovalores)
print("Autovectores: ", autovectores)

Autovalores:  [ 5. -1.]
Autovectores:  [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


$A = v . diag(\lambda) . v^{-1}$

donde:
- $v$: matriz de autovectores
- $diag(\lambda)$: matriz diagonal de autovalores

In [8]:
A_calc = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))
print(A_calc)

[[3. 2.]
 [4. 1.]]


### Ejemplo 2
Tenemos otras descomposiciones que tambien son muy útiles, en el caso que nuestra matriz A sea una matriz real (los números que la componen son reales) y simétrica ($A = A^t$)

In [12]:
A = np.array([[3,2],[2,3]])
print(A)

[[3 2]
 [2 3]]


Comprobamos si la matriz es simétrica, es decir: $A = A^t$

In [13]:
print(A == A.T)

[[ True  True]
 [ True  True]]


Ahora vamos a ver los autovalores y los autovectores

In [14]:
autovalores, autovectores = np.linalg.eig(A)
print(autovalores)
print(autovectores)

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


Las matrices simétricas se pueden des componer de la siguiente manera:

$A = v . diag(\lambda) . v^t$

donde:
- $v$: matriz de autovectores
- $diag(\lambda)$: matriz diagonal de autovalores

Recordemos que calcular una traspuesta es mucho más sencillo que calcular una inversa y computacionalmente más económico. Entonces, el caso ideal sería que en lugar de tener una matriz cualquiera tuviéramos una matriz real y simétrica.

In [15]:
A_calc = autovectores.dot(np.diag(autovalores)).dot(autovectores.T)
print(A_calc)

[[3. 2.]
 [2. 3.]]
